version: "3"
services: 
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
    app:
        build:
            context: ./OpenSocialApp.App
            dockerfile: Dockerfile
        ports: 
            - 5000:80
    api:
        build: 
            context: ./OpenSocialApp.Api
            dockerfile: Dockerfile
        ports: 
            - 5001:80
    sts:
        build: 
            context: ./OpenSocialApp.STS
            dockerfile: Dockerfile
        ports: 
            - 5002:80